### ISSUE TITLE
Stack trace on Civcraft

### ISSUE THREAD

**Issue by ttk2** [Civcraft/DynCap#2]
2015-01-19 11:25:25 [WARN] java.lang.ArrayIndexOutOfBoundsException: 14
2015-01-19 11:25:25 [WARN]      at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:454)
2015-01-19 11:25:25 [WARN]      at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2333)
2015-01-19 11:25:25 [WARN]      at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2248)
2015-01-19 11:25:25 [WARN]      at java.util.Calendar.complete(Calendar.java:1560)
2015-01-19 11:25:25 [WARN]      at java.util.Calendar.get(Calendar.java:1162)
2015-01-19 11:25:25 [WARN]      at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1093)
2015-01-19 11:25:25 [WARN]      at java.text.SimpleDateFormat.format(SimpleDateFormat.java:978)
2015-01-19 11:25:25 [WARN]      at java.text.SimpleDateFormat.format(SimpleDateFormat.java:948)
2015-01-19 11:25:25 [WARN]      at java.text.DateFormat.format(DateFormat.java:336)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.BanEntrySerializer.a(BanEntrySerializer.java:31)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.BanEntrySerializer.serialize(BanEntrySerializer.java:79)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.Gson.toJson(Gson.java:593)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.Gson.toJson(Gson.java:572)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.Gson.toJson(Gson.java:527)
2015-01-19 11:25:25 [WARN]      at net.minecraft.util.com.google.gson.Gson.toJson(Gson.java:507)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.UserCache.c(UserCache.java:214)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.UserCache.getProfile(UserCache.java:136)
2015-01-19 11:25:25 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getOfflinePlayer(CraftServer.java:1404)
2015-01-19 11:25:25 [WARN]      at com.untamedears.DynCap.DynCapPlugin.onAsyncPlayerPreLoginEvent(DynCapPlugin.java:124)
2015-01-19 11:25:25 [WARN]      at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
2015-01-19 11:25:25 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-01-19 11:25:25 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-01-19 11:25:25 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-01-19 11:25:25 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-01-19 11:25:25 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-01-19 11:25:25 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.fireLoginEvents(ThreadPlayerLookupUUID.java:79)
2015-01-19 11:25:25 [WARN]      at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:40)

**Comment by rourke750** [comment]
Maybe a one time occurrence?

**Comment by ttk2** [comment]
I have seen it a couple of times now, not that often, but enough to notice

**Comment by rourke750** [comment]
@erocs Would changing line 125 to 
synchronized(server){
			if(server.getBannedPlayers().contains(server.getOfflinePlayer(event.getUniqueId())))
			{
				event.disallow(AsyncPlayerPreLoginEvent.Result.KICK_BANNED, banMessage);
				return;
			}
			}
fix this issue where server is a class object?

**Comment by erocs** [comment]
Not unless every other use of server.getBannedPlayers also wraps it in a synchronized block.

**Comment by rourke750** [comment]
https://github.com/Civcraft/DynCap/commit/ad6cdcf65031af69377aff71692f3710ad3dbb3c

**Comment by ttk2** [comment]
sweet, does the jenkins build this?

**Comment by rourke750** [comment]
yes.

**Comment by ttk2** [comment]
http://192.99.169.83:8080/job/DynCap-master/4/

the build is called citadel.jar

**Comment by rourke750** [comment]
lol, it didnt have a maven repo looks like I derped

**Comment by rourke750** [comment]
check now

**Comment by ttk2** [comment]
on civtest, is that updated prisonpearl on Civtest from yesterday good?
does it need an update combat tag on the live server too or is it just not
ready?

**Comment by rourke750** [comment]
combat tag is fine on the live server.  I havent tested prisonpearl, it
should work but I'd rather make sure it wont fuck up.  We really need to
set up jira.

**Comment by ttk2** [comment]
Jira has always been nice but too hard to setup for us to get into using
it, we need somthing easier even if it means its less configurable
